### ISSUE TITLE
The "path" argument must be of type string.

### ISSUE THREAD

**Issue by JalenWasHere** [sensiolabs/StorybookBundle#44]
When running the Storybook watch server I keep running into the following error:

<details>

```
[vagrant@localhost project]$ yarn storybook-watch
yarn run v1.22.22
$ sb dev -p 6006 --no-open --disable-telemetry
@storybook/core v8.4.2

WARN The following packages are incompatible with Storybook 8.4.2 as they depend on different major versions of Storybook packages:
WARN - @storybook/cli@8.4.7
WARN  Repo: https://github.com/storybookjs/storybook/tree/next/code/lib/cli
WARN 
WARN 
WARN Please consider updating your packages or contacting the maintainers for compatibility details.
WARN For more on Storybook 8 compatibility, see the linked GitHub issue:
WARN https://github.com/storybookjs/storybook/issues/26031
(node:254156) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
info => Starting manager..
WARN No story files found for the specified pattern: stories/**/*.mdx
info => Starting preview..
[HPM] Proxy created: /  -> https://localhost
[HPM] Proxy created: /  -> https://localhost
[HPM] Proxy created: /  -> https://localhost
[HPM] Proxy created: /  -> https://localhost
=> Failed to build the preview
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at Object.join (node:path:1250:7)
    at base (./node_modules/@sensiolabs/storybook-symfony-webpack5/src/server/framework-preset.ts:101:11)
    at Array.map (<anonymous>)
    at base (./node_modules/@sensiolabs/storybook-symfony-webpack5/src/server/framework-preset.ts:101:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async base (./node_modules/@sensiolabs/storybook-symfony-webpack5/src/server/framework-preset.ts:101:11)
    at async starter (./node_modules/@sensiolabs/storybook-symfony-webpack5/node_modules/@storybook/builder-webpack5/dist/index.js:1:22057)
    at async Object.start (./node_modules/@sensiolabs/storybook-symfony-webpack5/node_modules/@storybook/builder-webpack5/dist/index.js:1:25862)
    at async storybookDevServer (./node_modules/storybook/node_modules/@storybook/core/dist/core-server/index.cjs:36000:11)
    at async buildOrThrow (./node_modules/storybook/node_modules/@storybook/core/dist/core-server/index.cjs:35017:12)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[vagrant@localhost project]$ 
```

</details>

These are the files I have:

```js
// .storybook/main.js

const config = {
  stories: ["../stories/**/*.stories.js", "../stories/**/*.mdx"],
  addons: [
    "@storybook/addon-webpack5-compiler-swc",
    "@storybook/addon-links",
    "@storybook/addon-essentials",
  ],
  framework: {
    name: "@sensiolabs/storybook-symfony-webpack5",
    options: {
      symfony: {
        server: 'https://localhost',
        proxyPaths: [
          '/assets',
          '/_components',
          '/components',
        ],
        additionalWatchPaths: [
          'assets',
        ]
      }
    },
  },
  docs: {
    autodocs: "tag",
  },
};

export default config;
```

```js
// stories/Button.stories.js
import Button from '../templates/components/Button.html.twig';

export default {
  component: Button,
};

export const Default = {};
```

```html
{#templates/components/Button.html.twig#}
<button
    type="{{ type|default('button') }}"
    class="flex items-center py-2 px-4 overflow-hidden text-white font-light text rounded-md transition-all ease-in-out duration-200 cursor-pointer hover:bg-company-darken focus:ring-4 focus:ring-blue-300 !bg-primary"
>
    <span class="font-poppins font-bold">
        {{ label }}
    </span>
    {% if icoon is defined %}
        <i class="bi bi-{{ icoon }} ml-1.5"></i>
    {% endif %}
</button>
```

```php
<?php
// src/Twig/Components/Button.php
namespace App\Twig\Components;

use Symfony\UX\TwigComponent\Attribute\AsTwigComponent;

#[AsTwigComponent(name: 'Button', template: 'components/Button.html.twig')]
class Button
{
    public string $type = 'success';
    public string $label = 'success';
    public string $message;
}
```

Is there something I'm missing? Any help would be greatly appreciated

**Comment by jmwamser** [comment]
Have you tried to run `yarn set version stable` and then install yarn and run build?

It is not the same as what I ran into on #34 but it could be something related.

**Comment by smepti** [comment]
I'am having the same problem on my working project. But if you download symfony demo and install bundle to those project - all will work perfect. Strange think, i will continue debugging tomorrow.

**Comment by smepti** [comment]
@JalenWasHere 
The problem for me was that the twig_component.anonymous_template_directory property was not defined. It's easy to check by running `bin/console debug:config twig_component --resolve-env`. If that's not your problem, then let me know.
Also you can clone the repository to your project and run the build in dev mode. Don't forget to change the path in package.json. In the raw js follow the stacktrace and debug :)

By the way. Isn't this a reason to add additional validation at startup to make the error clearer?

**Comment by JalenWasHere** [comment]
@smepti This indeed was the issue, thank you.
